##
# Basic Required Variables for tfscaffold Components
##

variable "project" {
  type        = string
  description = "The name of the tfscaffold project"
}

variable "environment" {
  type        = string
  description = "The name of the tfscaffold environment"
}

variable "component" {
  type        = string
  description = "The name of the tfscaffold component"
}

variable "aws_account_id" {
  type        = string
  description = "The AWS Account ID (numeric)"
}

variable "region" {
  type        = string
  description = "The AWS Region"
}

variable "group" {
  type        = string
  description = "The name of the tfscaffold group"
  default     = null
}

variable "kms_key_arn" {
  type        = string
  description = "KMS key arn to use for this function"
}

##
# tfscaffold variables specific to this module
##

variable "default_tags" {
  type        = map(string)
  description = "A map of default tags to apply to all taggable resources within the component"
  default     = {}
}

##
# Variables specific to this module
##

variable "function_name" {
  type        = string
  description = "Base name of this lambda"
}

variable "function_module_name" {
  type        = string
  description = "The name of the function module as used by the lambda handler, e.g. index or exports"
  default     = "index"
}

variable "description" {
  type        = string
  description = "Description of the Lambda"
}

variable "handler_function_name" {
  type        = string
  description = "The name of the lambda handler function (passed directly to the Lambda's handler option)"
  default     = "handler"
}

variable "memory" {
  type        = number
  description = "The amount of memory to apply to the created Lambda"
}

variable "timeout" {
  type        = number
  description = "Timeout in seconds of the lambda function invocation"
}

variable "log_retention_in_days" {
  type        = number
  description = "The retention period in days for the Cloudwatch Logs events generated by the lambda function"
}

variable "runtime" {
  type        = string
  description = "The runtime to use for the lambda function"
  default     = null

  validation {
    condition     = lower(var.package_type) != "zip" || (var.runtime != null && var.runtime != "")
    error_message = "runtime must be set when package_type is Zip."
  }
}

variable "package_type" {
  type        = string
  description = "Lambda package type: Zip or Image"
  default     = "Zip"

  validation {
    condition     = contains(["zip", "image"], lower(var.package_type))
    error_message = "package_type must be either Zip or Image."
  }
}

variable "image_uri" {
  type        = string
  description = "ECR image URI for Image-based Lambda"
  default     = null

  validation {
    condition     = lower(var.package_type) != "image" || (var.image_uri != null && var.image_uri != "")
    error_message = "image_uri must be set when package_type is Image."
  }
}

variable "image_config" {
  type = object({
    entry_point       = optional(list(string))
    command           = optional(list(string))
    working_directory = optional(string)
  })
  description = "Optional image configuration for Image-based Lambda"
  default     = null
}

variable "image_repository_names" {
  type        = list(string)
  description = "ECR repository names allowed for Image-based Lambda"
  default     = []

  validation {
    condition     = lower(var.package_type) != "image" || length(var.image_repository_names) > 0
    error_message = "image_repository_names must include at least one repository name when package_type is Image."
  }
}

variable "schedule" {
  type        = string
  description = "The fully qualified Cloudwatch Events schedule for when to run the lambda function, e.g. rate(1 day) or a cron() expression. Default disables all events resources"
  default     = ""
}

variable "iam_policy_document" {
  type = object({
    body = string
  })
  default = null
}

variable "lambda_env_vars" {
  type        = map(string)
  description = "Lambda environment parameters map"
  default     = {}
}

variable "function_code_base_path" {
  type        = string
  description = "The base path to the sourcecode directories needed for this lambda"
  default     = "./"
}

variable "function_code_dir" {
  type        = string
  description = "The directory for this lambda"
  default     = null

  validation {
    condition     = lower(var.package_type) != "zip" || (var.function_code_dir != null && var.function_code_dir != "")
    error_message = "function_code_dir must be set when package_type is Zip."
  }
}

variable "function_s3_bucket" {
  type        = string
  description = "The bucket to upload Lambda packages to"
  default     = null

  validation {
    condition     = lower(var.package_type) != "zip" || (var.function_s3_bucket != null && var.function_s3_bucket != "")
    error_message = "function_s3_bucket must be set when package_type is Zip."
  }
}

variable "function_include_common" {
  type        = bool
  description = "Include the 'common' lambda module with this lambda"
  default     = true
}

variable "force_lambda_code_deploy" {
  type        = bool
  description = "If the lambda package in s3 has the same commit id tag as the terraform build branch, the lambda will not update automatically. Set to True if making changes to Lambda code from on the same commit for example during development"
  default     = false
}

variable "log_level" {
  type        = string
  description = "The log level to be used in lambda functions within the component. Any log with a lower severity than the configured value will not be logged: https://docs.python.org/3/library/logging.html#levels"
  default     = "INFO"
}

variable "log_subscription_lambda_create_permission" {
  type        = bool
  description = "Whether to create a permission for the log forwarder. Set to false if using a generic one."
  default     = true
}

variable "layers" {
  type        = list(any)
  description = "Lambda layer arns to include"
  default     = []
}

variable "vpc_config" {
  type        = map(any)
  description = "Lambdas can run in a VPC, should be a map containing a subnet_ids list and a security_group_ids list"
  default     = null
}

variable "replace_security_groups_on_destroy" {
  type        = bool
  description = "Whether to swap Lambda security groups before destroy to reduce ENI-related SG deletion delays"
  default     = false
}

variable "replacement_security_group_ids" {
  type        = list(string)
  description = "Security group IDs to use for replacement when replace_security_groups_on_destroy is enabled"
  default     = []

  validation {
    condition     = !var.replace_security_groups_on_destroy || length(var.replacement_security_group_ids) > 0
    error_message = "replacement_security_group_ids must be set when replace_security_groups_on_destroy is true."
  }
}

variable "enable_dlq_and_notifications" {
  type        = bool
  description = "Create an SQS Queue and on-failure destination to be used as the Lambda's Dead Letter Queue and notifications"
  default     = false
}

variable "sns_destination" {
  type        = string
  description = "SNS Topic ARN to be used for on-failure Lambda invocation records"
  default     = null
}

variable "sns_destination_kms_key" {
  type        = string
  description = "KMS Key ARN to be used for SNS Topic for on-failure Lambda invocation records"
  default     = null
}

variable "lambda_dlq_message_retention_seconds" {
  type        = number
  description = "The number of seconds to retain messages in the Lambda DLQ SQS queue"
  default     = 1209600
}

variable "application_log_level" {
  type        = string
  description = "The detail level of the logs the application sends to CloudWatch"
  default     = "INFO"
}

variable "system_log_level" {
  type        = string
  description = "The detail level of the Lambda platform event logs sent to CloudWatch"
  default     = "WARN"
}

variable "enable_lambda_insights" {
  type        = bool
  description = "Enable the lambda insights layer, this must be disabled for lambda@edge usage"
  default     = true
}

variable "enable_xray_tracing" {
  type        = bool
  description = "Enable AWS X-Ray active tracing for the Lambda function."
  default     = false
}

variable "enable_error_rate_alarm" {
  type        = bool
  description = "Create a CloudWatch alarm when Lambda error rate exceeds the configured percentage threshold"
  default     = true
}

variable "lambda_error_rate_alarm_config" {
  description = "Object of optional CloudWatch alarm settings for the Lambda error rate alarm"
  type = object({
    comparison_operator = optional(string, "GreaterThanThreshold")
    evaluation_periods  = optional(number, 1)
    period              = optional(number, 300)
    threshold           = optional(number, 1)
    actions_enabled     = optional(bool, true)
    treat_missing_data  = optional(string, "notBreaching")
  })
  default = {}
}

variable "enable_throttles_alarm" {
  type        = bool
  description = "Create a CloudWatch alarm when Lambda throttles exceed the configured threshold"
  default     = true
}

variable "lambda_throttles_alarm_config" {
  description = "Object of optional CloudWatch alarm settings for the Lambda throttles alarm"
  type = object({
    comparison_operator = optional(string, "GreaterThanThreshold")
    evaluation_periods  = optional(number, 1)
    period              = optional(number, 300)
    statistic           = optional(string, "Sum")
    threshold           = optional(number, 0)
    actions_enabled     = optional(bool, true)
    treat_missing_data  = optional(string, "notBreaching")
  })
  default = {}
}

variable "enable_duration_alarm" {
  type        = bool
  description = "Create a CloudWatch alarm when Lambda duration percentile exceeds the configured threshold"
  default     = true
}

variable "lambda_duration_alarm_config" {
  description = "Object of optional CloudWatch alarm settings for the Lambda duration percentile alarm"
  type = object({
    comparison_operator = optional(string, "GreaterThanThreshold")
    evaluation_periods  = optional(number, 1)
    period              = optional(number, 300)
    percentile          = optional(string, "p95")
    threshold_ms        = optional(number)
    actions_enabled     = optional(bool, true)
    treat_missing_data  = optional(string, "notBreaching")
  })
  default = {}
}

variable "enable_dlq_messages_alarm" {
  type        = bool
  description = "Create a CloudWatch alarm when visible messages are present in the Lambda DLQ"
  default     = true
}

variable "lambda_dlq_messages_alarm_config" {
  description = "Object of optional CloudWatch alarm settings for the Lambda DLQ messages alarm"
  type = object({
    comparison_operator = optional(string, "GreaterThanThreshold")
    evaluation_periods  = optional(number, 1)
    period              = optional(number, 300)
    statistic           = optional(string, "Sum")
    threshold           = optional(number, 0)
    actions_enabled     = optional(bool, true)
    treat_missing_data  = optional(string, "notBreaching")
  })
  default = {}
}

variable "lambda_at_edge" {
  type        = bool
  description = "Whether this Lambda is a Lambda@Edge function"
  default     = false
}

variable "send_to_firehose" {
  type        = bool
  description = "Enable sending logs to firehose"
  default     = true
}

variable "filter_pattern" {
  type        = string
  description = "Filter pattern to use for the log subscription filter"
  default     = ""
}

variable "log_destination_arn" {
  type        = string
  description = "Destination ARN to use for the log subscription filter"
  default     = ""
}

variable "log_subscription_role_arn" {
  type        = string
  description = "The ARN of the IAM role to use for the log subscription filter"
  default     = ""
}

variable "permission_statements" {
  type = list(object({
    action         = optional(string)
    principal      = string
    source_arn     = optional(string)
    source_account = optional(string)
    statement_id   = string
  }))
  description = "Statements giving an external source permission to invoke the Lambda function"
  default     = []
}

variable "reserved_concurrent_executions" {
  type        = number
  description = "The reserved concurrency for the Lambda function. Set to -1 to remove the concurrency limit, or 0 to prevent the Lambda from being invoked."
  default     = -1
}
