name: "4. PR Title Check"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

permissions:
  contents: read

jobs:
  check-pr-title:
    name: "Check PR title"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Check PR title format"
        uses: ./.github/actions/check-pr-title-format
        with:
          title: ${{ github.event.pull_request.title }}
