name: Repository Template Sync

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  update-external-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Sync repository template
      uses: ./.github/actions/sync-template-repo
      with:
        github_token: ${{ github.token }}

    - name: Create Pull Request
      if: ${{ !env.ACT }}
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Drift from template
        branch: scheduledTemplateRepositorySync
        delete-branch: true
        title: '[Template Sync] Drift from template-repository remediation'
        body: |
          # Resultant drift from repository template

          ## Who should respond to this PR?
          The team which owns the responsibility for this component repository. You may want to consult other contributors.

          ## How to progress this PR
          The repositories guardians should review the contents of the PR and decide how to proceed, you may wish to back-out certain changes or accept them from the upstream `nhsdigital/nhs-notify-repository-template` repository.

          If there are changes you do not wish to see again, it is recommended you add exclusions to `scripts/config/.repository-template-sync-ignore`.
        labels: |
          template
          automation
        draft: false
